# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	bt_addr \
	irsc_util \
	netmgrd \
	qmiproxy \
	qmuxd \
	rmt_storage \
	sct_service \
	ta_qmi_service \
	tad_static \
	wcnss_addr \
	wcnss_service \
	MTP_Bluetooth_cal \
	MTP_General_cal \
	MTP_Global_cal \
	MTP_Handset_cal \
	MTP_Hdmi_cal \
	MTP_Headset_cal \
	MTP_Speaker_cal \
	QRD_Bluetooth_cal \
	QRD_General_cal \
	QRD_Global_cal \
	QRD_Handset_cal \
	QRD_Hdmi_cal \
	QRD_Headset_cal \
	QRD_Speaker_cal \
	a225_pfp \
	a225_pm4 \
	a225p5_pm4 \
	a300_pfp \
	a300_pm4 \
	a330_pfp \
	a330_pm4 \
	leia_pfp_470 \
	leia_pm4_470 \
	WCNSS_cfg \
	WCNSS_qcom_cfg \
	WCNSS_qcom_wlan_nv \
	copybit.msm8226 \
	libdiag \
	libkeyctrl \
	libmiscta \
	libmm-omxcore \
	libmmjpeg_interface \
	libpin-cache \
	libqomx_core \
	libta \
	libdrmwvmplugin \
	eglsubAndroid \
	libEGL_adreno \
	libGLESv1_CM_adreno \
	libGLESv2_adreno \
	libq3dtools_adreno \
	lib-dplmedia \
	lib-imsSDP \
	lib-imsdpl \
	lib-imsqimf \
	lib-imsrcs \
	lib-imss \
	lib-imsvt \
	lib-imsxml \
	lib-rcsimssjni \
	lib-rcsjni \
	lib-rtpcommon \
	lib-rtpcore \
	lib-rtpdaemoninterface \
	lib-rtpsl \
	libC2D2 \
	libCB \
	libCommandSvc \
	libDivxDrm \
	libExtendedExtractor \
	libFileMux \
	libHevcSwDecoder \
	libI420colorconvert \
	libNimsWrap \
	libOmxAacDec \
	libOmxAmrwbplusDec \
	libOmxEvrcDec \
	libOmxMux \
	libOmxQcelp13Dec \
	libOpenCL \
	libOpenVG \
	libQSEEComAPI \
	libRSDriver_adreno \
	libSHIMDivxDrm \
	libStDrvInt \
	libTimeService \
	libWVStreamControlAPI_L3 \
	libacdbloader \
	libacdbmapper \
	libacdbrtac \
	libadiertac \
	libadreno_utils \
	libadsprpc \
	libalarmservice_jni \
	libaudcal \
	libaudioalsa \
	libbtnv \
	libc2d2_z180 \
	libc2d30-a3xx \
	libc2d30-a4xx \
	libc2d30 \
	libcneapiclient \
	libcneconn \
	libcneqmiutils \
	libcneutils \
	libconfigdb \
	libdiagbridge \
	libdisp-aba \
	libdrmdiag \
	libdrmfs \
	libdrmtime \
	libdsi_netctrl \
	libdsnetutils \
	libdsucsd \
	libdsutils \
	libfastcvadsp_stub \
	libfastcvopt \
	libgeofence \
	libgsl \
	libidl \
	libizat_core \
	libjpegdhw \
	libjpegehw \
	liblbs_core \
	liblisten \
	liblistenhardware \
	liblistensoundmodel \
	libllvm-qcom \
	libloc2jnibridge \
	libmm-abl-oem \
	libmm-abl \
	libmm-color-convertor \
	libmm-hdcpmgr \
	libmmQSM \
	libmmQTA \
	libmmhttpstack \
	libmmiipstreammmihttp \
	libmmipl \
	libmmipstreamaal \
	libmmipstreamnetwork \
	libmmipstreamsourcehttp \
	libmmipstreamutils \
	libmmjpeg \
	libmmosal \
	libmmparser \
	libmmqjpeg_codec \
	libmmrtpdecoder \
	libmmrtpencoder \
	libmmwfdinterface \
	libmmwfdsinkinterface \
	libmmwfdsrcinterface \
	libmsapm_jni \
	libnetmgr \
	liboi_sbc_decoder \
	libprdrmdecrypt \
	libqc-opt \
	libqcci_legacy \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_csvt_srvc \
	libqmi_encdec \
	libqmiservices \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libquipc_os_api \
	libquipc_ulp_adapter \
	libril-qc-qmi-1 \
	libril-qcril-hook-oem \
	librpmb \
	librs_adreno \
	librs_adreno_sha1 \
	libsc-a2xx \
	libsc-a3xx \
	libscale \
	libscve \
	libsensor1 \
	libsensor_reg \
	libsrsprocessing \
	libssd \
	libsubsystem_control \
	libthermalclient \
	libthermalioctl \
	libtime_genoff \
	libtzdrmgenprov \
	libtzplayready \
	libulp2 \
	libwfdcommonutils \
	libwfdmmsink \
	libwfdmmsrc \
	libwfdmmutils \
	libwfdrtsp \
	libwfdsm \
	libwfduibcinterface \
	libwfduibcsink \
	libwfduibcsinkinterface \
	libwfduibcsrc \
	libwfduibcsrcinterface \
	libwifiscanner \
	libwvdrm_L3 \
	libxml \
	libxt_native \
	libxtadapter \
	libwvdrmengine \
	libadsp_denoise_skel \
	libdspCV_skel \
	libfastcvadsp \
	libfastcvadsp_skel \
	libqcbassboost \
	libqcreverb \
	libqcvirt
